{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bloodbank.fullname" . }}-mysql
  labels:
    {{- include "bloodbank.mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "bloodbank.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
{{- end }}


