apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.security.secretName }}
  labels:
    {{- include "bloodbank.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-username: {{ .Values.backend.env.spring.datasource.username }}
  db-password: {{ .Values.backend.env.spring.datasource.password }}
  mail-username: {{ .Values.backend.env.spring.mail.username }}
  mail-password: {{ .Values.backend.env.spring.mail.password }}


